name: dropxcult_app
description: "Dropxcult - Premium Streetwear"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  color: "#0D0D0D"
  android: true
  ios: true
  android_12:
    color: "#0D0D0D"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "WhatsApp Image 2025-12-16 at 8.24.36 PM.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: "WhatsApp Image 2025-12-16 at 8.24.36 PM.jpeg"

flutter:
  uses-material-design: true
